### ISSUE TITLE
getDriver().getWindowHandle() always returning "null" value with serenity-cucumber

### ISSUE THREAD

**Issue by narottamgla** [serenity-bdd/serenity-documentation#112]
**Below is the maven dependencies details:**
```
<serenity.version>1.5.9</serenity.version>
<serenity.cucumber.version>1.5.4</serenity.cucumber.version>
```

```
         <dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
```

And below is the line of code through which trying to print opened window id:

`        Log.info("Window handle::"+getDriver().getWindowHandle());
`
**Other details:**
- Win10 64 bit
- Chrome browser Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by wakaleo** [comment]
Could you post this in the serenity-core project? However, if it is Serenity returning null (and not WebDriver), it is usually because the test has failed in a previous step.

**Comment by wakaleo** [comment]
Closing as this is in the wrong repo.
