### ISSUE TITLE
Clarification needed on documentation about adding extra columns in result.csv

### ISSUE THREAD

**Issue by raytxz** [serenity-bdd/serenity-documentation#118]
Hi!

I am looking to add additional columns in the result.csv so that I can record some dynamic data generated during the run of the test. It seems like you can do this by adding properties to the serenity.property file.

I found the following in the documentation:
> serenity.csv.extra.columns
> Add extra columns to the CSV output, obtained from tag values.

So I added the following to my serenity.property:
serenity.csv.extra.columns = data1, data2

With this, I was able to add 2 new column in the result.csv. However, I cannot find in any documentations about how to output the required value from each test into this new column. I only see "tags" that are used for filtering test case, but not how to add the "tag values" that is mentioned in the documents above.

Could someone please help to clarify on the documentation? 

Thank you!

**Comment by raytxz** [comment]
Moving this to the google group instead.

https://groups.google.com/forum/#!topic/thucydides-users/_ug4ocgHQY8

**Comment by ramavijayakumar** [comment]
Did you find the solution for your issue? i am facing the same issue

**Comment by wakaleo** [comment]
This isn't currently supported.
