### ISSUE TITLE
Unclear documentation for serenity.timeout property

### ISSUE THREAD

**Issue by flaz14** [serenity-bdd/serenity-documentation#121]
The documentation for **serenity.timeout** property is unclear. As stated in "Running Serenity tests from the command line" chapter:

> **serenity.timeout**
> How long should the driver wait for elements not immediately visible.

As it can be guessed, the timeout should be specified in milliseconds (seconds are just too long spaces of time from webdriver's perspective). But it will be better to clearly say about unit of time like it's already done for `webdriver.timeouts.implicitlywait` and `webdriver.wait.for.timeout` properties.

**Comment by wakaleo** [comment]
PRs are welcome

**Comment by flaz14** [comment]
Hi @wakaleo,

I've just created PR: https://github.com/serenity-bdd/serenity-documentation/pull/122

**Comment by flaz14** [comment]
PR has been merged. So I close the issue. Thank you very much.
