### ISSUE TITLE
Documented webdriver.remote.url grid hub address format won't connect

### ISSUE THREAD

**Issue by foneox** [serenity-bdd/serenity-documentation#17]
It is documented [here](http://thucydides.info/docs/serenity-staging/#_running_remote_tests) that path to Selenium Grid Hub should be like this:
-Dwebdriver.remote.url=http://seleniumgrid:4444

But current implementation of serenity-core:1.1.1 expects full path to Grid Hub, e. g.:
-Dwebdriver.remote.url=http://seleniumgrid:4444**/wd/hub**

**Comment by wakaleo** [comment]
Thanks for pointing this out.
