### ISSUE TITLE
There is no detailed explanation of fields in aggregation report. 

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-documentation#44]
We have one issue serenity-bdd/serenity-core/issues/205, reason of it some miss understanding of reports. 

Lets include some short definition into basic-concepts chapter.

**Comment by RomanIshchenko** [comment]
If both row cases success total success =2

**Comment by RomanIshchenko** [comment]
I m not sure that I understend you as well
By the way I use standard example from official manual

**Comment by YamStranger** [comment]
@RomanIshchenko lets keep discussion about one issue in one place. As I understand your last comment about serenity-bdd/serenity-core#205 issue?

**Comment by YamStranger** [comment]
Fixed, and included in manual

**Comment by RomanIshchenko** [comment]
@YamStanger
Thanks a lot for your effort with it.
