### ISSUE TITLE
marking @manual scenarios  as PASS in serenity report

### ISSUE THREAD

**Issue by SubhasishC** [serenity-bdd/serenity-documentation#99]
Hi Team,

I want to mark all @manual scenarios as PASS in serenity report.

Is it possible ??

Please reply.

Thanks in Advance,
Subhasish

**Comment by wakaleo** [comment]
This is not supported at the moment because it could lead to misleading or incorrect reports, as they would imply that the version that was tested for the automated test run was also manually tested, which would be impossible in many cases (e.g. If the automated tests are part of a CI build).
